spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/newsletter_dashboard
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

app:
  file-processor:
    input-directory: ${user.dir}/dataSource/newsletter
    processed-directory: ${user.dir}/dataSource/newsletter/processed
    schedule-delay: 300000

newsletter:
  scheduler:
    csv:
      path: ${user.dir}/dataSource/selectedAudienceStatus

file:
  base-path: ${user.dir}

member-interactions:
  processing:
    cron: 0 0/2 0 * * *